# Generated by Django 5.0.6 on 2024-06-04 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course",
        ),
        migrations.RenameModel(
            old_name="Grades",
            new_name="Grade",
        ),
        migrations.RenameModel(
            old_name="Materials",
            new_name="Material",
        ),
        migrations.RenameModel(
            old_name="Mentors",
            new_name="Mentor",
        ),
        migrations.RenameModel(
            old_name="selectedMaterials",
            new_name="selectedMaterial",
        ),
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
