# Generated by Django 4.2.13 on 2024-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_rename_courses_course_rename_grades_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cous_name",
            field=models.CharField(help_text="enter course name", max_length=30),
        ),
    ]
